# Generated by Django 3.2.18 on 2023-03-01 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='../default_profile_klqque', upload_to='images/')),
                ('address', models.TextField(blank=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('fire_alarm', models.BooleanField(default=False)),
                ('emergency_lighting', models.BooleanField(default=False)),
                ('sprinkler_system', models.BooleanField(default=False)),
                ('gas', models.BooleanField(default=False)),
                ('asbestos', models.BooleanField(default=False)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
