# Generated by Django 3.2.18 on 2023-03-01 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
