# Generated by Django 3.2.18 on 2023-03-21 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assigned_to', '0001_initial'),
        ('master_tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField()),
                ('action_required', models.BooleanField(default=False)),
                ('action_description', models.TextField(blank=True)),
                ('action_by', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=32)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('file', models.FileField(blank=True, upload_to='files/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=32)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assigned_to.assignedto')),
                ('task_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_tasks.mastertask')),
            ],
            options={
                'ordering': ['task_name', 'assigned_to'],
            },
        ),
    ]
