# Generated by Django 3.2.18 on 2023-03-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertask',
            old_name='action_by',
            new_name='completed_by',
        ),
    ]
