# Generated by Django 3.2.18 on 2023-03-22 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_tasks', '0004_alter_usertask_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertask',
            options={'ordering': ['assigned_to']},
        ),
    ]
