# Generated by Django 3.2.18 on 2023-04-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tasks', '0006_auto_20230324_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='completed_by',
            field=models.CharField(choices=[('User', 'User'), ('Admin', 'Admin')], default='user', max_length=32),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='open', max_length=32),
        ),
    ]
