# Generated by Django 3.2.18 on 2023-04-26 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assigned_to', '0007_alter_assignedto_completed_by'),
        ('master_tasks', '0002_alter_mastertask_frequency'),
        ('user_tasks', '0009_alter_usertask_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertask',
            unique_together={('task_name', 'assigned_to')},
        ),
    ]
