# Generated by Django 3.2.18 on 2023-04-26 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_tasks', '0010_alter_usertask_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertask',
            unique_together=set(),
        ),
    ]
