# Generated by Django 3.2.18 on 2023-03-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_auto_20230321_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
