# Generated by Django 3.2.18 on 2023-04-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0007_alter_action_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='risk_rating',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='low', max_length=6),
        ),
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='open', max_length=12),
        ),
    ]
