# Generated by Django 3.2.18 on 2023-04-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertask',
            name='frequency',
            field=models.CharField(choices=[('Once', 'Once'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Biannually', 'Biannually'), ('Annually', 'Annually')], default='once', max_length=32),
        ),
    ]
