# Generated by Django 3.2.18 on 2023-03-21 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_due_date', models.DateField()),
                ('completed_by', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=32)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('task_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_tasks.mastertask')),
            ],
            options={
                'ordering': ['task_name', 'assigned_to'],
                'unique_together': {('owner', 'assigned_to')},
            },
        ),
    ]
