# Generated by Django 3.2.18 on 2023-03-24 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assigned_to', '0002_alter_assignedto_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedto',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignedto',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
