# Generated by Django 3.2.18 on 2023-04-19 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assigned_to', '0004_alter_assignedto_assigned_to'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignedto',
            unique_together=set(),
        ),
    ]
