# Generated by Django 3.2.18 on 2023-04-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assigned_to', '0005_alter_assignedto_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedto',
            name='completed_by',
            field=models.CharField(choices=[('User', 'User'), ('Admin', 'Admin')], default='user', max_length=32),
        ),
    ]
