# Generated by Django 3.2.18 on 2023-04-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assigned_to', '0006_alter_assignedto_completed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedto',
            name='completed_by',
            field=models.CharField(choices=[('User', 'User'), ('Admin', 'Admin')], default='User', max_length=32),
        ),
    ]
