# Generated by Django 3.2.18 on 2023-04-26 22:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_tasks', '0002_alter_mastertask_frequency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assigned_to', '0007_alter_assignedto_completed_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignedto',
            unique_together={('task_name', 'assigned_to')},
        ),
    ]
